CREATE TABLE IF NOT EXISTS os2_backup_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  backup_type ENUM('database','documents','full','verification') NOT NULL,
  status ENUM('queued','running','completed','failed','verified','expired') NOT NULL DEFAULT 'queued',
  database_name VARCHAR(128) NULL,
  storage_path VARCHAR(1024) NULL,
  file_name VARCHAR(255) NULL,
  checksum_sha256 CHAR(64) NULL,
  file_size_bytes BIGINT UNSIGNED NULL,
  table_count INT UNSIGNED NULL,
  row_count_estimate BIGINT UNSIGNED NULL,
  worker_id VARCHAR(160) NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  verified_at DATETIME NULL,
  failure_reason VARCHAR(1000) NULL,
  metadata_json JSON NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_backup_status_created (status,created_at),
  KEY idx_backup_type_created (backup_type,created_at),
  CONSTRAINT fk_backup_created_by FOREIGN KEY (created_by) REFERENCES staff_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS os2_restore_tests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  backup_run_id BIGINT UNSIGNED NOT NULL,
  status ENUM('planned','running','passed','failed','cancelled') NOT NULL DEFAULT 'planned',
  target_environment VARCHAR(120) NOT NULL DEFAULT 'isolated_preview_restore',
  expected_database_name VARCHAR(128) NOT NULL,
  actual_database_name VARCHAR(128) NULL,
  table_count INT UNSIGNED NULL,
  verified_checks INT UNSIGNED NULL,
  failed_checks INT UNSIGNED NULL,
  evidence_json JSON NULL,
  failure_reason VARCHAR(1000) NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_restore_backup (backup_run_id),
  KEY idx_restore_status_created (status,created_at),
  CONSTRAINT fk_restore_backup FOREIGN KEY (backup_run_id) REFERENCES os2_backup_runs(id),
  CONSTRAINT fk_restore_created_by FOREIGN KEY (created_by) REFERENCES staff_users(id),
  CONSTRAINT fk_restore_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES staff_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS os2_operational_checks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  check_type VARCHAR(100) NOT NULL,
  status ENUM('passed','warning','failed') NOT NULL,
  metric_value DECIMAL(20,4) NULL,
  metric_unit VARCHAR(40) NULL,
  details_json JSON NULL,
  checked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  worker_id VARCHAR(160) NULL,
  PRIMARY KEY (id),
  KEY idx_operational_check_type_time (check_type,checked_at),
  KEY idx_operational_check_status_time (status,checked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
