'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { parsePeriod, parseDueAt, detectIntent, nameSimilarity, staffFuzzyAllowed, clientAttentionIntent, numberWordsToDigits, shortStaffName, parseIndexSelector, clientAssignmentIntent } = require('../src/services/cudo-ai');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root,file),'utf8');

const server = read('server.js');
const layout = read('views/layout.ejs');
const shell = read('views/os-shell.ejs');
const route = read('src/routes/cudo-ai.js');
const service = read('src/services/cudo-ai.js');
const widget = read('public/js/cudo-widget.js');
const css = read('public/css/cudo-widget.css');
const assignmentService = read('src/services/cudo-client-assignment.js');
const officeAgent = read('src/services/office-intelligence-agent.js');

assert(server.includes("require('./src/routes/cudo-ai')"), 'Cudo route must be mounted');
assert(layout.includes('/public/js/cudo-widget.js'), 'Cudo must load on management layout pages');
assert(shell.includes('/public/js/cudo-widget.js'), 'Cudo must load on OS workspace');
assert(layout.includes('/public/css/cudo-widget.css'), 'Cudo layout CSS missing');
assert(shell.includes('/public/css/cudo-widget.css'), 'Cudo OS CSS missing');
assert(route.includes("router.post('/api/cudo/chat'"), 'Cudo chat API missing');
assert(route.includes("router.post('/api/cudo/action'"), 'Cudo action API missing');
assert(route.includes("actionName === 'confirm_reassignment'"), 'Cudo must confirm customer reassignment through the protected action endpoint');
assert(route.includes('reassignClientWork'), 'Cudo route must use the safe reassignment service');
assert(route.includes("router.get('/api/cudo/health', requireOwner"), 'Cudo health API must be owner-protected');
assert(route.includes("String(user.role || '').toLowerCase() === 'owner'"), 'Cudo API must be restricted to owner role');
assert(!route.includes('MANAGEMENT_ROLES'), 'Cudo must not allow manager/admin role shortcuts');
assert(service.includes('sendAgentInstruction'), 'Cudo must use existing monitored task path');
assert(service.includes('prepareClientReassignment'), 'Cudo must prepare customer reassignment from the current numbered result set');
assert(service.includes('shortStaffName(row.staff_name)'), 'Cudo result cards must display only staff first names');
assert(service.includes("shortStaffName(group.staffName)"), 'Cudo assignment previews must display only staff first names');
assert(service.includes('staffName: staff ? (staff.full_name || staff.username || staff.email) : null'), 'Cudo must retain the full resolved staff identity internally for safe matching');
assert(service.includes('assignmentDraft'), 'Cudo must keep a multi-turn assignment draft while waiting for a deadline');
assert(assignmentService.includes('cudo_client_reassigned'), 'Cudo reassignment must create an audit trail');
assert(assignmentService.includes('customer_accounts'), 'Cudo reassignment must preserve account-level ownership');
assert(assignmentService.includes('fixed_accounts'), 'Cudo reassignment must keep fixed account ownership aligned');
assert(assignmentService.includes('createAgentInstructionInTransaction'), 'Cudo reassignment must create monitored tasks atomically with assignment');
assert(officeAgent.includes('related_client_id'), 'Monitored Cudo assignment tasks must link back to the customer record');
assert(service.includes('agent'), 'Cudo service should remain connected to Gerda task foundation');
assert(widget.includes('t2m-cudo-position'), 'Cudo draggable position persistence missing');
assert(widget.includes('t2m-cudo-size'), 'Cudo resizable avatar persistence missing');
assert(widget.includes('activeContext'), 'Cudo current-screen context missing');
assert(widget.includes('SpeechRecognition'), 'Cudo browser speech recognition missing');
assert(widget.includes("root.querySelector('.cudo-mic')"), 'Cudo microphone control missing');
assert(widget.includes('recognition.start()'), 'Cudo microphone start behavior missing');
assert(widget.includes('recognition.onresult'), 'Cudo speech transcript handling missing');
assert(layout.includes("toLowerCase()==='owner'"), 'Cudo layout must be owner-only');
assert(shell.includes("toLowerCase()==='owner'"), 'Cudo OS shell must be owner-only');
assert(css.includes('resize:both'), 'Cudo panel resize affordance missing');
assert(fs.existsSync(path.join(root,'public/images/cudo-mascot.webp')), 'Cudo mascot asset missing');

const p = parsePeriod('show the last 6 months');
assert.equal(p.label,'the last 6 months');
assert(p.startSql && p.endSql);

const friday = parseDueAt('due Friday 15:00');
assert(friday && / 15:00:00$/.test(friday), 'Friday 15:00 deadline parsing failed');

assert.equal(detectIntent('How many of Johnny clients were followed up this month'), 'client_followup_activity');
assert.equal(detectIntent('Johnny outstanding upgrades this month'), 'upgrades');
assert.equal(detectIntent('What work has Gerda got left for today?'), 'office_work');
assert.equal(detectIntent('Show me the outstanding work for Stephan today'), 'office_work');
assert.equal(detectIntent('Was all staff members at work today?'), 'attendance');
assert.equal(detectIntent('Who is at work now?'), 'attendance');
assert.equal(detectIntent('Who was absent today?'), 'attendance');
assert.equal(detectIntent('Who came in late today?'), 'attendance');
assert.equal(detectIntent('Who left early today?'), 'attendance');
assert.equal(detectIntent('What time did Gerda arrive today?'), 'attendance');
assert.equal(detectIntent('What time did Johnny leave today?'), 'attendance');
assert.equal(detectIntent('Who has not clocked in yet?'), 'attendance');
assert.equal(detectIntent('Who worked the longest day today?'), 'attendance');
assert.equal(detectIntent('Who worked the shortest day today?'), 'attendance');
assert.equal(detectIntent('What work has Gerda got left for today?'), 'office_work', 'Task/work wording must not be stolen by attendance routing');
assert.equal(detectIntent('How many clients do we have in our database that have not been allocated to a staff member?'), 'unallocated_clients');
assert.equal(detectIntent('Show me customers without a staff allocation'), 'unallocated_clients');
assert.equal(detectIntent('Show me the items that needs attention'), 'client_attention');
assert.equal(detectIntent('Look into the clients and show me the clients that needs attention'), 'client_attention');
assert.equal(detectIntent('What customers must we contact?'), 'client_attention');
assert.equal(clientAttentionIntent('Who needs service today?'), true);
assert.equal(detectIntent('How many clients are unassigned?'), 'unallocated_clients');
assert.notEqual(detectIntent('How many clients are not allocated to staff?'), 'staff', 'Specific client allocation intent must beat generic staff wording');
assert(nameSimilarity('Stefan','Stephan') >= 0.95, 'Stefan should fuzzy-match Stephan');
assert(nameSimilarity('Gerta','Gerda') >= 0.79, 'Gerta should fuzzy-match Gerda');
assert(nameSimilarity('Jonny','Johnny') >= 0.79, 'Jonny should fuzzy-match Johnny');
assert.equal(staffFuzzyAllowed('Look into the clients and show me the clients that needs attention'), false, 'Ordinary CRM wording must never trigger fuzzy staff matching');
assert.equal(staffFuzzyAllowed('show outstanding upgrades for Jonny'), true, 'A staff-filter phrase should allow fuzzy staff matching');
assert.equal(staffFuzzyAllowed('give the first five to Brabet'), true, 'Assignment wording should allow fuzzy staff matching');
assert.equal(numberWordsToDigits('give five to Gerda'),'give 5 to Gerda');
assert.equal(shortStaffName('Jonathan Olivier'),'Jonathan');
assert.equal(shortStaffName('Brabant Allan Van Onselen'),'Brabant');
assert.equal(shortStaffName('gerda.le.roux@talk-online.co.za'),'gerda');
assert.deepEqual(parseIndexSelector('first five',[1,2,3,4,5,6,7],7),[1,2,3,4,5]);
assert.deepEqual(parseIndexSelector('1 to 5',[1,2,3,4,5,6,7],7),[1,2,3,4,5]);
assert.deepEqual(parseIndexSelector('items 1, 3 and 7',[1,2,3,4,5,6,7],7),[1,3,7]);
assert.deepEqual(parseIndexSelector('the rest',[6,7],7),[6,7]);
assert.equal(clientAssignmentIntent('give first five to Gerda',{selection:{kind:'upgrade',items:[{clientId:1}]}}),true);
assert.equal(clientAssignmentIntent('assign these as tasks to Gerda',{selection:{kind:'upgrade',items:[{clientId:1}]}}),false);
assert.equal(clientAssignmentIntent('give first five to Gerda',{selection:{kind:'client_attention',items:[{clientId:1}]}}),true);
assert(service.includes('queryClientAttention'), 'Cudo must have a broad client-attention CRM query');
assert(service.includes("directIntent === 'client_attention'"), 'Client-attention intent must route before staff-name resolution');
assert(service.includes('customer_followups'), 'Client attention must inspect customer follow-ups');
assert(service.includes('customer_callbacks'), 'Client attention must inspect callbacks');
assert(service.includes('Open inquiry needs attention'), 'Client attention must inspect open inquiries');
assert(service.includes('Customer task overdue since'), 'Client attention must inspect overdue customer tasks');
assert(service.includes('Birthday follow-up not recorded'), 'Client attention must inspect recent birthday follow-up gaps');
assert(service.includes('No staff member is allocated to this client'), 'Client attention must include unallocated clients');
assert(service.includes('queryClientFollowupActivity'), 'Client follow-up activity query missing');
assert(service.includes('buildDailyResponsibilities'), 'Cudo broad work must use the complete Gerda daily responsibility engine');
assert(!service.includes('f.updated_at'), 'Birthday/follow-up evidence must not reference missing follow-up updated_at');
assert(!service.includes('cb.updated_at'), 'Callback evidence must not reference missing callback updated_at');
assert(route.includes('logCudoError'), 'Cudo must log backend query failures with a reference');
assert(service.includes('queryUnallocatedClients'), 'Cudo must have a direct unallocated-client database tool');
assert(service.includes('queryAttendanceManagement'), 'Cudo must have a direct attendance/shop-management database tool');
assert(service.includes("require('./attendance')"), 'Cudo attendance must reuse the attendance schema');
assert(service.includes('attendance_sessions'), 'Cudo attendance must query attendance_sessions');
assert(service.includes('attendance_schedule_days'), 'Cudo attendance must use configured staff schedules');
assert(service.includes('late_grace_minutes'), 'Cudo attendance must use configured late grace');
assert(service.includes('staff_leave_records'), 'Cudo attendance must account for approved leave');
assert(service.includes("directIntent === 'attendance'"), 'Attendance intent must route before generic office/staff answers');
assert(service.includes('queryDatabaseFirstFallback'), 'Cudo must have a database-first fallback before clarification');
assert(service.includes('client_assignments'), 'Cudo allocation answers must query client_assignments');
assert(route.includes('evidence:result.evidence || null'), 'Cudo API must return database evidence');
assert(widget.includes('cudo-evidence'), 'Cudo UI must show what CRM data was checked');
assert(widget.includes('data-cudo-result-index'), 'Cudo result rows must be numbered');
assert(widget.includes('data-cudo-pick'), 'Cudo result rows must be individually selectable');
assert(widget.includes("assign_work:'Assign / reassign'"), 'Cudo must expose the assignment action');
assert(widget.includes('confirm_reassignment'), 'Cudo UI must support explicit assignment confirmation');
assert(css.includes('.cudo-result-number'), 'Cudo numbered result styling missing');
assert(css.includes('.cudo-pick'), 'Cudo result selection styling missing');
assert(css.includes('.cudo-evidence'), 'Cudo evidence styling missing');
assert(widget.includes('Voice transcript is ready in the box'), 'Voice must require transcript review before sending');
const voiceEnd = widget.slice(widget.indexOf('recognition.onend'), widget.indexOf('async function sendMessage'));
assert(!voiceEnd.includes('sendMessage(full)'), 'Voice recognition must not auto-submit');

console.log('CUDO_AI_VALIDATION=PASS');
