'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { parsePeriod, parseDueAt, detectIntent, nameSimilarity } = require('../src/services/cudo-ai');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root,file),'utf8');

const server = read('server.js');
const layout = read('views/layout.ejs');
const shell = read('views/os-shell.ejs');
const route = read('src/routes/cudo-ai.js');
const service = read('src/services/cudo-ai.js');
const widget = read('public/js/cudo-widget.js');
const css = read('public/css/cudo-widget.css');

assert(server.includes("require('./src/routes/cudo-ai')"), 'Cudo route must be mounted');
assert(layout.includes('/public/js/cudo-widget.js'), 'Cudo must load on management layout pages');
assert(shell.includes('/public/js/cudo-widget.js'), 'Cudo must load on OS workspace');
assert(layout.includes('/public/css/cudo-widget.css'), 'Cudo layout CSS missing');
assert(shell.includes('/public/css/cudo-widget.css'), 'Cudo OS CSS missing');
assert(route.includes("router.post('/api/cudo/chat'"), 'Cudo chat API missing');
assert(route.includes("router.post('/api/cudo/action'"), 'Cudo action API missing');
assert(route.includes("router.get('/api/cudo/health', requireOwner"), 'Cudo health API must be owner-protected');
assert(route.includes("String(user.role || '').toLowerCase() === 'owner'"), 'Cudo API must be restricted to owner role');
assert(!route.includes('MANAGEMENT_ROLES'), 'Cudo must not allow manager/admin role shortcuts');
assert(service.includes('sendAgentInstruction'), 'Cudo must use existing monitored task path');
assert(service.includes('agent'), 'Cudo service should remain connected to Gerda task foundation');
assert(widget.includes('t2m-cudo-position'), 'Cudo draggable position persistence missing');
assert(widget.includes('t2m-cudo-size'), 'Cudo resizable avatar persistence missing');
assert(widget.includes('activeContext'), 'Cudo current-screen context missing');
assert(widget.includes('SpeechRecognition'), 'Cudo browser speech recognition missing');
assert(widget.includes("root.querySelector('.cudo-mic')"), 'Cudo microphone control missing');
assert(widget.includes('recognition.start()'), 'Cudo microphone start behavior missing');
assert(widget.includes('recognition.onresult'), 'Cudo speech transcript handling missing');
assert(layout.includes("toLowerCase()==='owner'"), 'Cudo layout must be owner-only');
assert(shell.includes("toLowerCase()==='owner'"), 'Cudo OS shell must be owner-only');
assert(css.includes('resize:both'), 'Cudo panel resize affordance missing');
assert(fs.existsSync(path.join(root,'public/images/cudo-mascot.webp')), 'Cudo mascot asset missing');

const p = parsePeriod('show the last 6 months');
assert.equal(p.label,'the last 6 months');
assert(p.startSql && p.endSql);

const friday = parseDueAt('due Friday 15:00');
assert(friday && / 15:00:00$/.test(friday), 'Friday 15:00 deadline parsing failed');

assert.equal(detectIntent('How many of Johnny clients were followed up this month'), 'client_followup_activity');
assert.equal(detectIntent('Johnny outstanding upgrades this month'), 'upgrades');
assert.equal(detectIntent('What work has Gerda got left for today?'), 'office_work');
assert.equal(detectIntent('Show me the outstanding work for Stephan today'), 'office_work');
assert.equal(detectIntent('Was all staff members at work today?'), 'attendance');
assert.equal(detectIntent('Who is at work now?'), 'attendance');
assert.equal(detectIntent('Who was absent today?'), 'attendance');
assert.equal(detectIntent('Who came in late today?'), 'attendance');
assert.equal(detectIntent('Who left early today?'), 'attendance');
assert.equal(detectIntent('What time did Gerda arrive today?'), 'attendance');
assert.equal(detectIntent('What time did Johnny leave today?'), 'attendance');
assert.equal(detectIntent('Who has not clocked in yet?'), 'attendance');
assert.equal(detectIntent('Who worked the longest day today?'), 'attendance');
assert.equal(detectIntent('Who worked the shortest day today?'), 'attendance');
assert.equal(detectIntent('What work has Gerda got left for today?'), 'office_work', 'Task/work wording must not be stolen by attendance routing');
assert.equal(detectIntent('How many clients do we have in our database that have not been allocated to a staff member?'), 'unallocated_clients');
assert.equal(detectIntent('Show me customers without a staff allocation'), 'unallocated_clients');
assert.equal(detectIntent('How many clients are unassigned?'), 'unallocated_clients');
assert.notEqual(detectIntent('How many clients are not allocated to staff?'), 'staff', 'Specific client allocation intent must beat generic staff wording');
assert(nameSimilarity('Stefan','Stephan') >= 0.95, 'Stefan should fuzzy-match Stephan');
assert(nameSimilarity('Gerta','Gerda') >= 0.79, 'Gerta should fuzzy-match Gerda');
assert(nameSimilarity('Jonny','Johnny') >= 0.79, 'Jonny should fuzzy-match Johnny');
assert(service.includes('queryClientFollowupActivity'), 'Client follow-up activity query missing');
assert(service.includes('buildDailyResponsibilities'), 'Cudo broad work must use the complete Gerda daily responsibility engine');
assert(!service.includes('f.updated_at'), 'Birthday/follow-up evidence must not reference missing follow-up updated_at');
assert(!service.includes('cb.updated_at'), 'Callback evidence must not reference missing callback updated_at');
assert(route.includes('logCudoError'), 'Cudo must log backend query failures with a reference');
assert(service.includes('queryUnallocatedClients'), 'Cudo must have a direct unallocated-client database tool');
assert(service.includes('queryAttendanceManagement'), 'Cudo must have a direct attendance/shop-management database tool');
assert(service.includes("require('./attendance')"), 'Cudo attendance must reuse the attendance schema');
assert(service.includes('attendance_sessions'), 'Cudo attendance must query attendance_sessions');
assert(service.includes('attendance_schedule_days'), 'Cudo attendance must use configured staff schedules');
assert(service.includes('late_grace_minutes'), 'Cudo attendance must use configured late grace');
assert(service.includes('staff_leave_records'), 'Cudo attendance must account for approved leave');
assert(service.includes("directIntent === 'attendance'"), 'Attendance intent must route before generic office/staff answers');
assert(service.includes('queryDatabaseFirstFallback'), 'Cudo must have a database-first fallback before clarification');
assert(service.includes('client_assignments'), 'Cudo allocation answers must query client_assignments');
assert(route.includes('evidence:result.evidence || null'), 'Cudo API must return database evidence');
assert(widget.includes('cudo-evidence'), 'Cudo UI must show what CRM data was checked');
assert(css.includes('.cudo-evidence'), 'Cudo evidence styling missing');
assert(widget.includes('Voice transcript is ready in the box'), 'Voice must require transcript review before sending');
const voiceEnd = widget.slice(widget.indexOf('recognition.onend'), widget.indexOf('async function sendMessage'));
assert(!voiceEnd.includes('sendMessage(full)'), 'Voice recognition must not auto-submit');

console.log('CUDO_AI_VALIDATION=PASS');
