const express = require('express');
const helmet = require('helmet');
const cookieParser = require('cookie-parser');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const path = require('path');
const { query, getPool } = require('./db');
const { calculateDay, decimalHours } = require('./payroll');

const TEST_IDS = new Set(String(process.env.TEST_USER_IDS || '1,3').split(',').map(x=>Number(x.trim())).filter(Boolean));
const ADMIN_ROLES = new Set(String(process.env.ADMIN_ROLE_IDS || '1,2').split(',').map(x=>Number(x.trim())).filter(Boolean));
const isTestMode = () => String(process.env.TEST_MODE || 'true').toLowerCase() === 'true';
const tokenFrom = req => (req.headers.authorization || '').replace(/^Bearer\s+/i,'') || req.cookies?.pest_token || '';
function sign(user){ return jwt.sign({id:user.id, role_id:user.role_id, company_id:user.company_id, name:user.full_name}, process.env.JWT_SECRET, {expiresIn:process.env.JWT_EXPIRES_IN||'7d'}); }
function auth(req,res,next){ try { req.user=jwt.verify(tokenFrom(req),process.env.JWT_SECRET); next(); } catch { res.status(401).json({success:false,message:'Please log in again.'}); } }
function admin(req,res,next){ if(!ADMIN_ROLES.has(Number(req.user.role_id))) return res.status(403).json({success:false,message:'Administrator access required.'}); next(); }
function tester(req,res,next){ if(isTestMode() && !TEST_IDS.has(Number(req.user.id))) return res.status(403).json({success:false,message:'The new app is currently restricted to approved testers.'}); next(); }
function haversine(a,b,c,d){ const R=6371000, r=x=>x*Math.PI/180, p1=r(a),p2=r(c),dp=r(c-a),dl=r(d-b); const q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2; return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q)); }
async function audit(userId, companyId, action, entityType, entityId, details, req){ try { const sessionId=entityType==='work_session'?entityId:null; const staffId=details?.target_staff_id||null; await query(`INSERT INTO admin_audit_log (company_id,admin_user_id,action_type,target_staff_id,target_session_id,reason,meta_json,created_at) VALUES (?,?,?,?,?,?,?,NOW())`,[companyId||1,userId||0,action,staffId,sessionId,String(details?.reason||action).slice(0,255),JSON.stringify({...details,ip_address:req.ip,user_agent:String(req.headers['user-agent']||'').slice(0,255)})]); } catch(e){ console.error('Audit warning:',e.message); } }
async function worksitesFor(userId){ return query(`SELECT w.*,uw.is_primary FROM user_worksites uw JOIN worksites w ON w.id=uw.worksite_id WHERE uw.user_id=? AND uw.is_active=1 AND w.is_active=1 ORDER BY uw.is_primary DESC,uw.id DESC`,[userId]); }
async function worksiteFor(userId){ const rows=await worksitesFor(userId); return rows[0]||null; }
async function nearestAssignedWorksite(userId,lat,lon){ const rows=await worksitesFor(userId); let best=null; for(const w of rows){ const wlat=Number(w.latitude),wlon=Number(w.longitude); if(!Number.isFinite(wlat)||!Number.isFinite(wlon)) continue; const distance=haversine(lat,lon,wlat,wlon); if(!best||distance<best.distance_meters) best={...w,distance_meters:distance}; } return best; }
async function openSession(userId){ const rows=await query(`SELECT * FROM work_sessions WHERE user_id=? AND session_status='OPEN' AND clock_out_time IS NULL ORDER BY id DESC LIMIT 1`,[userId]); return rows[0]||null; }
function ymd(d=new Date()){ return new Intl.DateTimeFormat('en-CA',{timeZone:process.env.APP_TIMEZONE||'Africa/Johannesburg',year:'numeric',month:'2-digit',day:'2-digit'}).format(d); }

async function start(){
 const app=express(); app.set('trust proxy',1); app.use(helmet({contentSecurityPolicy:false})); app.use(express.json({limit:'1mb'})); app.use(express.urlencoded({extended:true})); app.use(cookieParser());
 app.get('/api/health',async(req,res)=>{ try{await query('SELECT 1');res.json({success:true,service:'pest-workforce-platform',version:'2.3.0',database:'connected',test_mode:isTestMode(),allowed_test_users:[...TEST_IDS]});}catch(e){res.status(500).json({success:false,database:'disconnected',message:e.message});}});
 app.post('/api/auth/login',async(req,res)=>{ const id=String(req.body.identifier||'').trim(), pw=String(req.body.password||''); const rows=await query(`SELECT id,company_id,full_name,first_name,last_name,email,phone,staff_code,role_id,password_hash,is_active FROM users WHERE is_active=1 AND (email=? OR phone=? OR staff_code=? OR employee_code=?) LIMIT 1`,[id,id,id,id]); const u=rows[0]; if(!u) return res.status(401).json({success:false,message:'Incorrect login details.'}); const hash=String(u.password_hash).replace(/^\$2y\$/,'$2b$'); if(!await bcrypt.compare(pw,hash)) return res.status(401).json({success:false,message:'Incorrect login details.'}); if(isTestMode()&&!TEST_IDS.has(Number(u.id))) return res.status(403).json({success:false,message:'This test release is currently available only to Johan and Stephan.'}); const token=sign(u); await query('UPDATE users SET last_login_at=NOW() WHERE id=?',[u.id]); res.cookie('pest_token',token,{httpOnly:true,secure:true,sameSite:'lax',maxAge:7*86400000}); res.json({success:true,token,user:{id:u.id,full_name:u.full_name,role_id:u.role_id,email:u.email,phone:u.phone}}); });
 app.post('/api/auth/logout',(req,res)=>{res.clearCookie('pest_token');res.json({success:true});});
 app.get('/api/me',auth,async(req,res)=>{const rows=await query('SELECT id,company_id,full_name,email,phone,staff_code,role_id FROM users WHERE id=?',[req.user.id]);res.json({success:true,user:rows[0]});});
 app.get('/api/my-worksite',auth,tester,async(req,res)=>{res.json({success:true,worksite:await worksiteFor(req.user.id)});});
 app.get('/api/attendance/status',auth,tester,async(req,res)=>{const s=await openSession(req.user.id);let lunch=0;if(s){const r=await query(`SELECT worked_minutes FROM work_session_events WHERE work_session_id=? AND event_type='WORKING_LUNCH' ORDER BY id DESC LIMIT 1`,[s.id]);lunch=Number(r[0]?.worked_minutes||0);}res.json({success:true,open_session:s,working_lunch_minutes:lunch});});
 app.get('/api/attendance/history',auth,tester,async(req,res)=>{const rows=await query(`SELECT ws.*,w.name worksite_name FROM work_sessions ws LEFT JOIN worksites w ON w.id=ws.worksite_id WHERE ws.user_id=? ORDER BY ws.clock_in_time DESC LIMIT 60`,[req.user.id]);res.json({success:true,sessions:rows});});
 app.post('/api/attendance/clock-in',auth,tester,async(req,res)=>{const lat=Number(req.body.latitude),lon=Number(req.body.longitude),acc=Number(req.body.accuracy_meters||0);if(!Number.isFinite(lat)||!Number.isFinite(lon))return res.status(422).json({success:false,message:'GPS location is required.'});if(await openSession(req.user.id))return res.status(409).json({success:false,message:'You are already clocked in.'});const w=await nearestAssignedWorksite(req.user.id,lat,lon);if(!w)return res.status(404).json({success:false,message:'No active worksite is assigned.'});const dist=Number(w.distance_meters||0),allowed=Number(w.allowed_radius_meters||0),status=allowed<=0||dist<=allowed?'ON_SITE':'OUTSIDE_RADIUS';const r=await query(`INSERT INTO work_sessions (company_id,user_id,worksite_id,session_date,clock_in_time,clock_in_latitude,clock_in_longitude,clock_in_accuracy_meters,clock_in_distance_meters,clock_in_ip_address,clock_in_device_info,clock_in_status,session_status) VALUES (?,?,?,CURDATE(),NOW(),?,?,?,?,?,?,?,'OPEN')`,[req.user.company_id,req.user.id,w.id,lat,lon,acc,dist,req.ip,String(req.headers['user-agent']||'').slice(0,255),status]);await audit(req.user.id,req.user.company_id,'CLOCK_IN','work_session',r.insertId,{status,distance_meters:dist,source:'node-v2'},req);res.json({success:true,message:status==='ON_SITE'?'Clock-in successful.':'Clock-in successful. Outside radius flagged for review.',work_session_id:r.insertId,clock_in_status:status,distance_meters:Math.round(dist)});});
 app.post('/api/attendance/working-lunch',auth,tester,async(req,res)=>{const mins=Number(req.body.worked_minutes),lat=Number(req.body.latitude),lon=Number(req.body.longitude),acc=Number(req.body.accuracy_meters||0);if(![15,30,45,60].includes(mins))return res.status(422).json({success:false,message:'Choose 15, 30, 45 or 60 minutes.'});if(!Number.isFinite(lat)||!Number.isFinite(lon))return res.status(422).json({success:false,message:'GPS location is required to record worked lunch.'});const s=await openSession(req.user.id);if(!s)return res.status(404).json({success:false,message:'Clock in first.'});const exists=await query(`SELECT id,worked_minutes FROM work_session_events WHERE work_session_id=? AND event_type='WORKING_LUNCH' LIMIT 1`,[s.id]);if(exists[0])return res.status(409).json({success:false,message:`Working lunch already recorded: ${exists[0].worked_minutes||0} minutes.`});const w=await nearestAssignedWorksite(req.user.id,lat,lon);if(!w)return res.status(404).json({success:false,message:'No active worksite is assigned.'});const dist=Number(w.distance_meters||0),allowed=Number(w.allowed_radius_meters||0),status=allowed<=0||dist<=allowed?'ON_SITE':'OUTSIDE_RADIUS';const evidence=JSON.stringify({matched_worksite_id:w.id,matched_worksite_name:w.name,allowed_radius_meters:allowed});await query(`INSERT INTO work_session_events (company_id,work_session_id,user_id,event_type,event_status,event_reason,event_time,latitude,longitude,accuracy_meters,distance_meters,device_info,notes,worked_minutes,created_at) VALUES (?,?,?,'WORKING_LUNCH',?,?,NOW(),?,?,?,?,?,?,?,NOW())`,[req.user.company_id,s.id,req.user.id,status,evidence,lat,lon,acc,dist,String(req.headers['user-agent']||'').slice(0,255),`Worked lunch minutes: ${mins}`,mins]);await audit(req.user.id,req.user.company_id,'WORKING_LUNCH','work_session',s.id,{minutes:mins,status,distance_meters:dist,matched_worksite_id:w.id,source:'node-v2'},req);res.json({success:true,message:status==='ON_SITE'?`Working lunch recorded: ${mins} minutes.`:`Working lunch recorded: ${mins} minutes. Outside radius flagged for review.`,worked_lunch_minutes:mins,working_lunch_status:status,distance_meters:Math.round(dist),matched_worksite:{id:w.id,name:w.name}});});
 app.post('/api/attendance/clock-out',auth,tester,async(req,res)=>{const lat=Number(req.body.latitude),lon=Number(req.body.longitude),acc=Number(req.body.accuracy_meters||0);if(!Number.isFinite(lat)||!Number.isFinite(lon))return res.status(422).json({success:false,message:'GPS location is required.'});const s=await openSession(req.user.id);if(!s)return res.status(404).json({success:false,message:'No open session found.'});const w=await nearestAssignedWorksite(req.user.id,lat,lon),dist=Number(w?.distance_meters||0),allowed=Number(w?.allowed_radius_meters||0),status=!w||allowed<=0||dist<=allowed?'ON_SITE':'OUTSIDE_RADIUS';await query(`UPDATE work_sessions SET clock_out_time=NOW(),clock_out_latitude=?,clock_out_longitude=?,clock_out_accuracy_meters=?,clock_out_distance_meters=?,clock_out_ip_address=?,clock_out_device_info=?,clock_out_status=?,session_status='CLOSED',closed_by_type='staff',closed_by_id=?,worked_minutes=TIMESTAMPDIFF(MINUTE,clock_in_time,NOW()),updated_at=NOW() WHERE id=?`,[lat,lon,acc,dist,req.ip,String(req.headers['user-agent']||'').slice(0,255),status,req.user.id,s.id]);await audit(req.user.id,req.user.company_id,'CLOCK_OUT','work_session',s.id,{status,distance_meters:dist,source:'node-v2'},req);res.json({success:true,message:'Clock-out successful.',clock_out_status:status});});

 app.get('/api/admin/dashboard',auth,admin,async(req,res)=>{const [[staff],[open],[today],[exceptions]] = await Promise.all([query('SELECT COUNT(*) total FROM users WHERE is_active=1'),query("SELECT COUNT(*) total FROM work_sessions WHERE session_status='OPEN'"),query('SELECT COUNT(*) total FROM work_sessions WHERE session_date=CURDATE()'),query("SELECT COUNT(*) total FROM work_sessions WHERE needs_review=1 OR clock_in_status='OUTSIDE_RADIUS' OR clock_out_status='OUTSIDE_RADIUS'")]);res.json({success:true,stats:{staff:staff.total,open:open.total,today:today.total,exceptions:exceptions.total},test_mode:isTestMode()});});
 app.get('/api/admin/staff',auth,admin,async(req,res)=>{const rows=await query(`SELECT u.id,u.full_name,u.staff_code,u.email,u.phone,u.role_id,u.is_active,w.name worksite FROM users u LEFT JOIN user_worksites uw ON uw.user_id=u.id AND uw.is_active=1 AND uw.is_primary=1 LEFT JOIN worksites w ON w.id=uw.worksite_id ORDER BY u.full_name`);res.json({success:true,staff:rows});});
 app.get('/api/admin/worksites',auth,admin,async(req,res)=>{res.json({success:true,worksites:await query('SELECT * FROM worksites ORDER BY name')});});
 app.get('/api/admin/sessions',auth,admin,async(req,res)=>{const from=req.query.from||ymd(new Date(Date.now()-30*86400000)),to=req.query.to||ymd();const rows=await query(`SELECT ws.*,u.full_name,w.name worksite_name,w.latitude worksite_latitude,w.longitude worksite_longitude,w.allowed_radius_meters,e.id working_lunch_event_id,e.worked_minutes working_lunch_minutes,e.event_time working_lunch_time,e.event_status working_lunch_status,e.event_reason working_lunch_reason,e.latitude working_lunch_latitude,e.longitude working_lunch_longitude,e.accuracy_meters working_lunch_accuracy_meters,e.distance_meters working_lunch_distance_meters,e.device_info working_lunch_device_info FROM work_sessions ws JOIN users u ON u.id=ws.user_id LEFT JOIN worksites w ON w.id=ws.worksite_id LEFT JOIN work_session_events e ON e.id=(SELECT e2.id FROM work_session_events e2 WHERE e2.work_session_id=ws.id AND e2.event_type='WORKING_LUNCH' ORDER BY e2.id DESC LIMIT 1) WHERE ws.session_date BETWEEN ? AND ? ORDER BY ws.clock_in_time DESC LIMIT 2000`,[from,to]);const userSites=new Map();for(const row of rows){if(row.working_lunch_reason){try{const meta=JSON.parse(row.working_lunch_reason);row.working_lunch_worksite_id=meta.matched_worksite_id||null;row.working_lunch_worksite_name=meta.matched_worksite_name||null;row.working_lunch_allowed_radius_meters=meta.allowed_radius_meters??null;}catch{}}let sites=userSites.get(row.user_id);if(!sites){sites=await worksitesFor(row.user_id);userSites.set(row.user_id,sites);}if(row.working_lunch_worksite_id){const m=sites.find(w=>Number(w.id)===Number(row.working_lunch_worksite_id));if(m){row.working_lunch_worksite_name=m.name;row.working_lunch_worksite_latitude=m.latitude;row.working_lunch_worksite_longitude=m.longitude;row.working_lunch_allowed_radius_meters=m.allowed_radius_meters;}}else if(row.working_lunch_event_id&&row.working_lunch_latitude!=null&&row.working_lunch_longitude!=null){const lat=Number(row.working_lunch_latitude),lon=Number(row.working_lunch_longitude);let best=null;for(const w of sites){const wlat=Number(w.latitude),wlon=Number(w.longitude);if(!Number.isFinite(wlat)||!Number.isFinite(wlon))continue;const distance=haversine(lat,lon,wlat,wlon);if(!best||distance<best.distance_meters)best={...w,distance_meters:distance};}if(best){row.working_lunch_worksite_id=best.id;row.working_lunch_worksite_name=best.name;row.working_lunch_worksite_latitude=best.latitude;row.working_lunch_worksite_longitude=best.longitude;row.working_lunch_allowed_radius_meters=best.allowed_radius_meters;row.working_lunch_distance_meters=row.working_lunch_distance_meters??best.distance_meters;const allowed=Number(best.allowed_radius_meters||0);row.working_lunch_status=row.working_lunch_status||(allowed<=0||best.distance_meters<=allowed?'ON_SITE':'OUTSIDE_RADIUS');}}}res.json({success:true,sessions:rows});});
 app.post('/api/admin/sessions/:id/manual-close',auth,admin,async(req,res)=>{const id=Number(req.params.id),when=req.body.clock_out_time;if(!when)return res.status(422).json({success:false,message:'clock_out_time is required.'});await query(`UPDATE work_sessions SET clock_out_time=?,clock_out_status='MANUAL',session_status='CLOSED',closed_by_type='admin',closed_by_id=?,close_reason=?,needs_review=1,worked_minutes=TIMESTAMPDIFF(MINUTE,clock_in_time,?),updated_at=NOW() WHERE id=?`,[when,req.user.id,String(req.body.reason||'Manual close'),when,id]);await audit(req.user.id,req.user.company_id,'MANUAL_CLOSE','work_session',id,{when,reason:req.body.reason},req);res.json({success:true});});
 app.get('/api/admin/payroll',auth,admin,async(req,res)=>{const from=req.query.from||ymd(new Date(Date.now()-30*86400000)),to=req.query.to||ymd(),staffId=Number(req.query.staff_id||0);const staffSql=staffId?' AND ws.user_id=?':'';const staffParams=staffId?[staffId]:[];const sessions=await query(`SELECT ws.*,DATE_FORMAT(ws.session_date,'%Y-%m-%d') session_date,u.full_name FROM work_sessions ws JOIN users u ON u.id=ws.user_id WHERE ws.session_date BETWEEN ? AND ?${staffSql} ORDER BY u.full_name,ws.session_date,ws.clock_in_time`,[from,to,...staffParams]);const lunches=await query(`SELECT ws.user_id,DATE_FORMAT(ws.session_date,'%Y-%m-%d') session_date,SUM(COALESCE(e.worked_minutes,0)) minutes FROM work_session_events e JOIN work_sessions ws ON ws.id=e.work_session_id WHERE e.event_type='WORKING_LUNCH' AND ws.session_date BETWEEN ? AND ?${staffSql} GROUP BY ws.user_id,ws.session_date`,[from,to,...staffParams]);const adjSql=staffId?' AND user_id=?':'';const adjs=await query(`SELECT user_id,DATE_FORMAT(adjustment_date,'%Y-%m-%d') adjustment_date,SUM(normal_minutes_adjustment) normal,SUM(ot_15_minutes_adjustment) ot15,SUM(ot_20_minutes_adjustment) ot20 FROM payroll_adjustments WHERE adjustment_date BETWEEN ? AND ? AND status='ACTIVE'${adjSql} GROUP BY user_id,adjustment_date`,[from,to,...staffParams]);const map=new Map();for(const s of sessions){const date=String(s.session_date).slice(0,10),k=`${s.user_id}|${date}`;if(!map.has(k))map.set(k,{user_id:s.user_id,full_name:s.full_name,date,sessions:[]});map.get(k).sessions.push(s);}const lm=new Map(lunches.map(x=>[`${x.user_id}|${String(x.session_date).slice(0,10)}`,Number(x.minutes)])),am=new Map(adjs.map(x=>[`${x.user_id}|${String(x.adjustment_date).slice(0,10)}`,x]));const days=[];for(const [k,g] of map){const date=new Date(g.date+'T12:00:00'),dow=date.getDay(),dayType=dow===0?'SUNDAY':'WEEKDAY',a=am.get(k)||{};const c=calculateDay({sessions:g.sessions,workingLunchMinutes:lm.get(k)||0,adjustments:{normal:Number(a.normal||0),ot15:Number(a.ot15||0),ot20:Number(a.ot20||0)},dayType});days.push({...g,...c,normal_hours:decimalHours(c.normalMinutes),ot15_hours:decimalHours(c.ot15Minutes),ot20_hours:decimalHours(c.ot20Minutes)});}res.json({success:true,from,to,staff_id:staffId||null,days});});
 app.get('/api/admin/payroll/sage.csv',auth,admin,async(req,res)=>{const from=req.query.from||ymd(new Date(Date.now()-30*86400000)),to=req.query.to||ymd();const sessions=await query(`SELECT ws.*,DATE_FORMAT(ws.session_date,'%Y-%m-%d') session_date,u.full_name,u.employee_code FROM work_sessions ws JOIN users u ON u.id=ws.user_id WHERE ws.session_date BETWEEN ? AND ? ORDER BY u.full_name,ws.session_date,ws.clock_in_time`,[from,to]);const lunches=await query(`SELECT ws.user_id,DATE_FORMAT(ws.session_date,'%Y-%m-%d') session_date,SUM(COALESCE(e.worked_minutes,0)) minutes FROM work_session_events e JOIN work_sessions ws ON ws.id=e.work_session_id WHERE e.event_type='WORKING_LUNCH' AND ws.session_date BETWEEN ? AND ? GROUP BY ws.user_id,ws.session_date`,[from,to]);const adjs=await query(`SELECT user_id,DATE_FORMAT(adjustment_date,'%Y-%m-%d') adjustment_date,SUM(normal_minutes_adjustment) normal,SUM(ot_15_minutes_adjustment) ot15,SUM(ot_20_minutes_adjustment) ot20 FROM payroll_adjustments WHERE adjustment_date BETWEEN ? AND ? AND status='ACTIVE' GROUP BY user_id,adjustment_date`,[from,to]);const lm=new Map(lunches.map(x=>[`${x.user_id}|${x.session_date}`,Number(x.minutes)])),am=new Map(adjs.map(x=>[`${x.user_id}|${x.adjustment_date}`,x]));const groups=new Map();for(const s of sessions){const k=`${s.user_id}|${s.session_date}`;if(!groups.has(k))groups.set(k,{user_id:s.user_id,employee_code:s.employee_code||'',full_name:s.full_name,date:s.session_date,sessions:[]});groups.get(k).sessions.push(s);}const totals=new Map();for(const [k,g] of groups){const a=am.get(k)||{},dow=new Date(g.date+'T12:00:00').getDay(),c=calculateDay({sessions:g.sessions,workingLunchMinutes:lm.get(k)||0,adjustments:{normal:Number(a.normal||0),ot15:Number(a.ot15||0),ot20:Number(a.ot20||0)},dayType:dow===0?'SUNDAY':'WEEKDAY'});const t=totals.get(g.user_id)||{employee_code:g.employee_code,full_name:g.full_name,ot15:0,ot20:0};t.ot15+=c.ot15Minutes;t.ot20+=c.ot20Minutes;totals.set(g.user_id,t);}const lines=['Employee Code,Overtime 1.5 - Units,Overtime 1.5 - Amount,Overtime 2.0 - Units,Overtime 2.0 - Amount'];for(const t of [...totals.values()].sort((a,b)=>a.employee_code.localeCompare(b.employee_code))){lines.push([t.employee_code,decimalHours(t.ot15).toFixed(2),'',decimalHours(t.ot20).toFixed(2),''].join(','));}res.setHeader('Content-Type','text/csv');res.setHeader('Content-Disposition',`attachment; filename="sage-payroll-totals-${from}-to-${to}.csv"`);res.send(lines.join('\n'));});
 app.get('/api/admin/roles',auth,admin,async(req,res)=>{res.json({success:true,roles:await query('SELECT id,name,description FROM roles ORDER BY id')});});
 app.get('/api/admin/audit',auth,admin,async(req,res)=>{const rows=await query(`SELECT a.*,u.full_name admin_name,s.full_name target_staff_name FROM admin_audit_log a LEFT JOIN users u ON u.id=a.admin_user_id LEFT JOIN users s ON s.id=a.target_staff_id ORDER BY a.id DESC LIMIT 500`);res.json({success:true,audit:rows});});
 app.get('/api/admin/assignments',auth,admin,async(req,res)=>{const rows=await query(`SELECT uw.id,uw.user_id,uw.worksite_id,uw.is_primary,uw.is_active,uw.assigned_from,uw.assigned_to,u.full_name,w.name worksite_name FROM user_worksites uw JOIN users u ON u.id=uw.user_id JOIN worksites w ON w.id=uw.worksite_id ORDER BY uw.is_active DESC,u.full_name,w.name`);res.json({success:true,assignments:rows});});
 app.post('/api/admin/assignments',auth,admin,async(req,res)=>{const userId=Number(req.body.user_id),worksiteId=Number(req.body.worksite_id),primary=req.body.is_primary?1:0;if(!userId||!worksiteId)return res.status(422).json({success:false,message:'Staff member and worksite are required.'});if(primary)await query('UPDATE user_worksites SET is_primary=0 WHERE user_id=?',[userId]);const existing=await query('SELECT id FROM user_worksites WHERE user_id=? AND worksite_id=? LIMIT 1',[userId,worksiteId]);if(existing[0])await query('UPDATE user_worksites SET is_active=1,is_primary=?,assigned_from=COALESCE(assigned_from,CURDATE()),assigned_to=NULL WHERE id=?',[primary,existing[0].id]);else await query('INSERT INTO user_worksites (company_id,user_id,worksite_id,is_primary,is_active,assigned_from,created_at) VALUES (?,?,?,?,1,CURDATE(),NOW())',[req.user.company_id,userId,worksiteId,primary]);await audit(req.user.id,req.user.company_id,'ASSIGN_WORKSITE','user_worksite',existing[0]?.id||null,{target_staff_id:userId,worksite_id:worksiteId,is_primary:primary},req);res.json({success:true});});
 app.post('/api/admin/assignments/:id/deactivate',auth,admin,async(req,res)=>{const id=Number(req.params.id);const rows=await query('SELECT user_id FROM user_worksites WHERE id=?',[id]);await query('UPDATE user_worksites SET is_active=0,assigned_to=CURDATE() WHERE id=?',[id]);await audit(req.user.id,req.user.company_id,'DEACTIVATE_ASSIGNMENT','user_worksite',id,{target_staff_id:rows[0]?.user_id},req);res.json({success:true});});
 app.post('/api/admin/staff',auth,admin,async(req,res)=>{const full=String(req.body.full_name||'').trim(),email=String(req.body.email||'').trim()||null,phone=String(req.body.phone||'').trim()||null,code=String(req.body.staff_code||'').trim();if(!full||!code||!req.body.password)return res.status(422).json({success:false,message:'Full name, staff code and password are required.'});const parts=full.split(/\s+/),first=parts.shift()||full,last=parts.join(' ')||'-',hash=await bcrypt.hash(String(req.body.password),12);const r=await query(`INSERT INTO users (company_id,staff_code,full_name,role_id,employee_code,first_name,last_name,email,phone,password_hash,is_active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,1,NOW(),NOW())`,[req.user.company_id,code,full,Number(req.body.role_id||3),String(req.body.employee_code||code),first,last,email,phone,hash]);await audit(req.user.id,req.user.company_id,'CREATE_STAFF','user',r.insertId,{target_staff_id:r.insertId},req);res.json({success:true,id:r.insertId});});
 app.post('/api/admin/staff/:id/status',auth,admin,async(req,res)=>{const id=Number(req.params.id),active=req.body.is_active?1:0;await query('UPDATE users SET is_active=?,updated_at=NOW() WHERE id=?',[active,id]);await audit(req.user.id,req.user.company_id,active?'ACTIVATE_STAFF':'DEACTIVATE_STAFF','user',id,{target_staff_id:id},req);res.json({success:true});});
 app.post('/api/admin/worksites',auth,admin,async(req,res)=>{const b=req.body;if(!b.name||!b.code||!Number.isFinite(Number(b.latitude))||!Number.isFinite(Number(b.longitude)))return res.status(422).json({success:false,message:'Name, code, latitude and longitude are required.'});const r=await query(`INSERT INTO worksites (company_id,code,name,address_line_1,city,province,postal_code,country,latitude,longitude,allowed_radius_meters,strict_geofence,is_active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,1,NOW(),NOW())`,[req.user.company_id,b.code,b.name,b.address_line_1||null,b.city||null,b.province||null,b.postal_code||null,b.country||'South Africa',Number(b.latitude),Number(b.longitude),Number(b.allowed_radius_meters||100),b.strict_geofence?1:0]);await audit(req.user.id,req.user.company_id,'CREATE_WORKSITE','worksite',r.insertId,{name:b.name},req);res.json({success:true,id:r.insertId});});
 app.post('/api/admin/worksites/:id/status',auth,admin,async(req,res)=>{const id=Number(req.params.id),active=req.body.is_active?1:0;await query('UPDATE worksites SET is_active=?,updated_at=NOW() WHERE id=?',[active,id]);await audit(req.user.id,req.user.company_id,active?'ACTIVATE_WORKSITE':'DEACTIVATE_WORKSITE','worksite',id,{},req);res.json({success:true});});
 app.get('/api/admin/adjustments',auth,admin,async(req,res)=>{const from=req.query.from||ymd(new Date(Date.now()-30*86400000)),to=req.query.to||ymd();const rows=await query(`SELECT p.*,u.full_name FROM payroll_adjustments p JOIN users u ON u.id=p.user_id WHERE p.adjustment_date BETWEEN ? AND ? ORDER BY p.adjustment_date DESC,p.id DESC`,[from,to]);res.json({success:true,adjustments:rows});});
 app.post('/api/admin/adjustments',auth,admin,async(req,res)=>{const b=req.body,userId=Number(b.user_id);if(!userId||!b.adjustment_date||!b.reason)return res.status(422).json({success:false,message:'Staff, date and reason are required.'});const r=await query(`INSERT INTO payroll_adjustments (company_id,user_id,adjustment_date,adjustment_type,leave_type,is_paid,normal_minutes_adjustment,ot_15_minutes_adjustment,ot_20_minutes_adjustment,reason,approved_by_user_id,status,approved_by,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,'ACTIVE',?,?,NOW(),NOW())`,[req.user.company_id,userId,b.adjustment_date,b.adjustment_type||'MANUAL',b.leave_type||null,b.is_paid===false?0:1,Number(b.normal_minutes_adjustment||0),Number(b.ot_15_minutes_adjustment||0),Number(b.ot_20_minutes_adjustment||0),String(b.reason),req.user.id,req.user.id,req.user.id]);await audit(req.user.id,req.user.company_id,'CREATE_ADJUSTMENT','payroll_adjustment',r.insertId,{target_staff_id:userId,reason:b.reason},req);res.json({success:true,id:r.insertId});});
 app.post('/api/admin/adjustments/:id/void',auth,admin,async(req,res)=>{const id=Number(req.params.id),reason=String(req.body.reason||'Voided by administrator');const rows=await query('SELECT user_id FROM payroll_adjustments WHERE id=?',[id]);await query(`UPDATE payroll_adjustments SET status='VOID',void_reason=?,voided_by_user_id=?,voided_at=NOW(),updated_at=NOW() WHERE id=?`,[reason,req.user.id,id]);await audit(req.user.id,req.user.company_id,'VOID_ADJUSTMENT','payroll_adjustment',id,{target_staff_id:rows[0]?.user_id,reason},req);res.json({success:true});});
 app.get('/api/admin/payroll-settings',auth,admin,async(req,res)=>{const rows=await query('SELECT * FROM payroll_settings ORDER BY id DESC LIMIT 1');res.json({success:true,settings:rows[0]||null});});
 app.post('/api/admin/payroll-settings',auth,admin,async(req,res)=>{const b=req.body,rows=await query('SELECT id FROM payroll_settings ORDER BY id DESC LIMIT 1');if(rows[0])await query(`UPDATE payroll_settings SET normal_start_time=?,normal_end_time=?,grace_before_minutes=?,grace_after_minutes=?,standard_daily_minutes=?,lunch_minutes=?,updated_at=NOW() WHERE id=?`,[b.normal_start_time,b.normal_end_time,Number(b.grace_before_minutes),Number(b.grace_after_minutes),Number(b.standard_daily_minutes),Number(b.lunch_minutes),rows[0].id]);else await query(`INSERT INTO payroll_settings (normal_start_time,normal_end_time,grace_before_minutes,grace_after_minutes,standard_daily_minutes,lunch_minutes) VALUES (?,?,?,?,?,?)`,[b.normal_start_time,b.normal_end_time,Number(b.grace_before_minutes),Number(b.grace_after_minutes),Number(b.standard_daily_minutes),Number(b.lunch_minutes)]);await audit(req.user.id,req.user.company_id,'UPDATE_PAYROLL_SETTINGS','payroll_settings',rows[0]?.id||null,{reason:'Payroll settings updated'},req);res.json({success:true});});


 app.get('/api/admin/company-setup',auth,admin,async(req,res)=>{const c=(await query('SELECT * FROM companies WHERE id=? LIMIT 1',[req.user.company_id]))[0]||null;const cs=(await query('SELECT * FROM company_settings WHERE company_id=? LIMIT 1',[req.user.company_id]))[0]||null;const ps=(await query('SELECT * FROM payroll_settings ORDER BY id DESC LIMIT 1'))[0]||null;res.json({success:true,company:c,company_settings:cs,payroll_settings:ps});});
 app.post('/api/admin/company-setup',auth,admin,async(req,res)=>{const b=req.body,c=b.company||{},cs=b.company_settings||{},ps=b.payroll_settings||{};await query(`UPDATE companies SET company_name=?,trading_name=?,logo_path=?,primary_color=?,secondary_color=?,accent_color=?,danger_color=?,contact_email=?,contact_phone=?,address_line_1=?,address_line_2=?,city=?,region=?,postal_code=?,timezone=?,updated_at=NOW() WHERE id=?`,[c.company_name,c.trading_name||null,c.logo_path||null,c.primary_color||null,c.secondary_color||null,c.accent_color||null,c.danger_color||null,c.contact_email||null,c.contact_phone||null,c.address_line_1||null,c.address_line_2||null,c.city||null,c.region||null,c.postal_code||null,c.timezone||'Africa/Johannesburg',req.user.company_id]);const csr=await query('SELECT id FROM company_settings WHERE company_id=? LIMIT 1',[req.user.company_id]);if(csr[0])await query(`UPDATE company_settings SET default_radius_meters=?,clock_in_geofence_mode=?,clock_out_geofence_mode=?,allow_multiple_sessions_per_day=?,enable_midnight_auto_close=?,auto_close_time=?,auto_close_reason_text=?,updated_at=NOW() WHERE id=?`,[Number(cs.default_radius_meters||150),cs.clock_in_geofence_mode||'SOFT',cs.clock_out_geofence_mode||'SOFT',cs.allow_multiple_sessions_per_day?1:0,cs.enable_midnight_auto_close?1:0,cs.auto_close_time||'23:59:59',cs.auto_close_reason_text||'Auto-closed at midnight',csr[0].id]);const pr=await query('SELECT id FROM payroll_settings ORDER BY id DESC LIMIT 1');if(pr[0])await query(`UPDATE payroll_settings SET normal_start_time=?,normal_end_time=?,grace_before_minutes=?,grace_after_minutes=?,standard_daily_minutes=?,lunch_minutes=?,updated_at=NOW() WHERE id=?`,[ps.normal_start_time||'07:30:00',ps.normal_end_time||'16:30:00',Number(ps.grace_before_minutes||10),Number(ps.grace_after_minutes||10),Number(ps.standard_daily_minutes||480),Number(ps.lunch_minutes||60),pr[0].id]);await audit(req.user.id,req.user.company_id,'UPDATE_COMPANY_SETUP','company',req.user.company_id,{reason:'Company setup updated'},req);res.json({success:true});});
 app.get('/api/admin/exceptions',auth,admin,async(req,res)=>{const from=req.query.from||ymd(new Date(Date.now()-30*86400000)),to=req.query.to||ymd();const rows=await query(`SELECT ws.*,u.full_name,w.name worksite_name FROM work_sessions ws JOIN users u ON u.id=ws.user_id LEFT JOIN worksites w ON w.id=ws.worksite_id WHERE ws.session_date BETWEEN ? AND ? AND (ws.needs_review=1 OR ws.clock_in_status='OUTSIDE_RADIUS' OR ws.clock_out_status='OUTSIDE_RADIUS' OR ws.clock_out_time IS NULL OR ws.closed_by_type='auto') ORDER BY ws.session_date DESC,ws.clock_in_time DESC`,[from,to]);res.json({success:true,exceptions:rows});});
 app.get('/api/admin/leave-report',auth,admin,async(req,res)=>{const from=req.query.from||ymd(new Date(Date.now()-30*86400000)),to=req.query.to||ymd();const rows=await query(`SELECT p.*,DATE_FORMAT(p.adjustment_date,'%Y-%m-%d') adjustment_date,u.full_name,u.employee_code FROM payroll_adjustments p JOIN users u ON u.id=p.user_id WHERE p.adjustment_date BETWEEN ? AND ? AND p.status='ACTIVE' AND (p.adjustment_type='LEAVE' OR p.leave_type IS NOT NULL) ORDER BY p.adjustment_date,u.full_name`,[from,to]);res.json({success:true,leave:rows});});
 app.get('/api/admin/period-totals',auth,admin,async(req,res)=>{const from=req.query.from||ymd(new Date(Date.now()-30*86400000)),to=req.query.to||ymd();const sessions=await query(`SELECT ws.*,DATE_FORMAT(ws.session_date,'%Y-%m-%d') session_date,u.full_name,u.employee_code FROM work_sessions ws JOIN users u ON u.id=ws.user_id WHERE ws.session_date BETWEEN ? AND ? ORDER BY u.full_name,ws.session_date,ws.clock_in_time`,[from,to]);const lunches=await query(`SELECT ws.user_id,DATE_FORMAT(ws.session_date,'%Y-%m-%d') session_date,SUM(COALESCE(e.worked_minutes,0)) minutes FROM work_session_events e JOIN work_sessions ws ON ws.id=e.work_session_id WHERE e.event_type='WORKING_LUNCH' AND ws.session_date BETWEEN ? AND ? GROUP BY ws.user_id,ws.session_date`,[from,to]);const adjs=await query(`SELECT user_id,DATE_FORMAT(adjustment_date,'%Y-%m-%d') adjustment_date,SUM(normal_minutes_adjustment) normal,SUM(ot_15_minutes_adjustment) ot15,SUM(ot_20_minutes_adjustment) ot20 FROM payroll_adjustments WHERE adjustment_date BETWEEN ? AND ? AND status='ACTIVE' GROUP BY user_id,adjustment_date`,[from,to]);const lm=new Map(lunches.map(x=>[`${x.user_id}|${x.session_date}`,Number(x.minutes)])),am=new Map(adjs.map(x=>[`${x.user_id}|${x.adjustment_date}`,x])),days=new Map();for(const s of sessions){const k=`${s.user_id}|${s.session_date}`;if(!days.has(k))days.set(k,{user_id:s.user_id,employee_code:s.employee_code||'',full_name:s.full_name,date:s.session_date,sessions:[]});days.get(k).sessions.push(s);}const totals=new Map();for(const [k,g] of days){const a=am.get(k)||{},dow=new Date(g.date+'T12:00:00').getDay(),c=calculateDay({sessions:g.sessions,workingLunchMinutes:lm.get(k)||0,adjustments:{normal:Number(a.normal||0),ot15:Number(a.ot15||0),ot20:Number(a.ot20||0)},dayType:dow===0?'SUNDAY':'WEEKDAY'});const t=totals.get(g.user_id)||{user_id:g.user_id,employee_code:g.employee_code,full_name:g.full_name,normal:0,ot15:0,ot20:0,lunch:0,days:0};t.normal+=c.normalMinutes;t.ot15+=c.ot15Minutes;t.ot20+=c.ot20Minutes;t.lunch+=c.workingLunchMinutes;t.days++;totals.set(g.user_id,t);}res.json({success:true,from,to,totals:[...totals.values()].sort((a,b)=>a.full_name.localeCompare(b.full_name))});});
 app.use(express.static(path.join(__dirname,'..','public'),{extensions:['html']})); app.get('/backoffice/*s',(req,res)=>res.sendFile(path.join(__dirname,'..','public','backoffice','index.html'))); app.get('*s',(req,res)=>res.sendFile(path.join(__dirname,'..','public','index.html')));
 const port=Number(process.env.PORT||3000); await getPool().query('SELECT 1'); app.listen(port,'0.0.0.0',()=>console.log(`Pest Workforce v2.3.0 listening on ${port}`));
}
module.exports={start};
