-- Talk2Me Issue #57 - Monthly Dealer Data Import Centre, Phase 1
-- ONE-OFF SQL ONLY. Back up the production database before applying.
-- Do not run npm run db:migrate.

CREATE TABLE IF NOT EXISTS monthly_import_batches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  import_type ENUM('activation','upgrade','fixed_base') NOT NULL,
  source_system ENUM('B12','SIEBEL','FIXED_BASE') NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  file_hash CHAR(64) NOT NULL,
  report_start_date DATE NULL,
  report_end_date DATE NULL,
  dealer_id VARCHAR(80) NULL,
  total_rows INT UNSIGNED NOT NULL DEFAULT 0,
  valid_rows INT UNSIGNED NOT NULL DEFAULT 0,
  duplicate_rows INT UNSIGNED NOT NULL DEFAULT 0,
  exception_rows INT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('preview','confirmed','cancelled','failed') NOT NULL DEFAULT 'preview',
  imported_by INT NULL,
  confirmed_by INT NULL,
  confirmed_at DATETIME NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_monthly_import_batches_hash (file_hash),
  KEY ix_monthly_import_batches_period (report_start_date,report_end_date),
  KEY ix_monthly_import_batches_status (status),
  CONSTRAINT fk_monthly_import_batches_imported_by FOREIGN KEY (imported_by) REFERENCES staff_users(id) ON DELETE SET NULL,
  CONSTRAINT fk_monthly_import_batches_confirmed_by FOREIGN KEY (confirmed_by) REFERENCES staff_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS monthly_import_rows (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_row_number INT UNSIGNED NOT NULL,
  row_fingerprint CHAR(64) NOT NULL,
  import_status ENUM('staged','confirmed','duplicate','exception','failed') NOT NULL DEFAULT 'staged',
  phone_original VARCHAR(80) NULL,
  phone_normalised VARCHAR(20) NULL,
  account_number VARCHAR(120) NULL,
  customer_name VARCHAR(255) NULL,
  transaction_date DATE NULL,
  agent_code VARCHAR(120) NULL,
  deal_sheet_number VARCHAR(120) NULL,
  imei VARCHAR(80) NULL,
  order_number VARCHAR(120) NULL,
  mac_address VARCHAR(120) NULL,
  solution_id VARCHAR(120) NULL,
  sim_number VARCHAR(120) NULL,
  package_name VARCHAR(255) NULL,
  description TEXT NULL,
  matched_client_id INT NULL,
  matched_account_id INT NULL,
  raw_data_json LONGTEXT NOT NULL,
  warning_text TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_monthly_import_rows_batch_row (batch_id,source_row_number),
  KEY ix_monthly_import_rows_fingerprint (row_fingerprint),
  KEY ix_monthly_import_rows_phone (phone_normalised),
  KEY ix_monthly_import_rows_account (account_number),
  KEY ix_monthly_import_rows_status (import_status),
  CONSTRAINT fk_monthly_import_rows_batch FOREIGN KEY (batch_id) REFERENCES monthly_import_batches(id) ON DELETE CASCADE,
  CONSTRAINT fk_monthly_import_rows_client FOREIGN KEY (matched_client_id) REFERENCES clients(id) ON DELETE SET NULL,
  CONSTRAINT fk_monthly_import_rows_account FOREIGN KEY (matched_account_id) REFERENCES customer_accounts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
